### ISSUE TITLE
Highlight boxes and misc visual designs

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-website-design#100]
Apologies if we have this stuff listed elsewhere. I didn't find it, and wanted to get it down before I forgot.

I think we still need visual design of a few types of highlight boxes and such, including for things such as these:
* Overview box in https://www.w3.org/WAI/users/inaccessible
* Top of https://www.w3.org/WAI/intro/accessibility
* E-mail templates bottom of https://www.w3.org/WAI/users/inaccessible
* Examples middle of https://www.w3.org/WAI/users/inaccessible
* Examples in https://www.w3.org/WAI/gettingstarted/tips/designing.html
* Examples in tutorials, e.g, https://w3c.github.io/wai-website/tutorials/page-structure/headings/
* @@ . . .

I assume we want more uniform visual designs for similar things, e.g., examples. :-)

**Comment by yatil** [comment]
We have the boxes already. I don’t know why this is an open issue.

https://w3c.github.io/wai-website-components/components/detail/box-wrapper--default.html

We just have to decide which style to use where and apply that. Some examples need editorial work. I will take care of most of it and defer to the editors where needed/more efficient.

EDIT: Especially I think we have all the design templates for this, so nothing @aliciafrausto needs to care about :-D

**Comment by shawna-slh** [comment]
OK, I'll close it for now.

We'll need to see them implemented to see if we all think they work well.

**Comment by yatil** [comment]
> We'll need to see them implemented to see if we all think they work well.

We currently don’t use them anywhere. I get no directions on where to use them, so I do not just use them somewhere. We have examples for those boxes in the tutorials and the tips. They have been implemented according to the finished design. 

I reopen this issue because I did not get any direction which bo to use where and therefore this issue is not resolved.

**Comment by yatil** [comment]
> Examples in tutorials, e.g, https://w3c.github.io/wai-website/tutorials/page-structure/headings/

Also, in this instance example images are missing because we are _in the process_ of porting content into the new design. We have to touch every page and make sure it is right. We will not do that before the content is OK’d and we cannot do it before we haven't the implementation in HTML done.

It is not helpful to conflate bugs present in the prototype with content that has not been adapted with missing visuals. We need to keep that separate.

**Comment by aliciafrausto** [comment]
https://visa.invisionapp.com/share/YPAVCUZA9#/223719140_Graphics
These are the elements I've already created styles for, for reference. 

It seems like that box Eric created plus what is in the mocks will cover the list up above, but let me know if not.

**Comment by yatil** [comment]
* Overview box in https://www.w3.org/WAI/users/inaccessible
* E-mail templates bottom of https://www.w3.org/WAI/users/inaccessible
* Examples middle of https://www.w3.org/WAI/users/inaccessible

Implemented with standard boxes here: https://w3c.github.io/wai-contacting-orgs/

* Top of https://www.w3.org/WAI/intro/accessibility

Unclear what this refers to. To the text “A shorter introduction is available here: Accessibility - W3C”? We don’t currently have something like that and I can think about if really needed.

* Examples in https://www.w3.org/WAI/gettingstarted/tips/designing.html

https://wai-quick-start.netlify.com/tips/designing/

* Examples in tutorials, e.g, https://w3c.github.io/wai-website/tutorials/page-structure/headings/

https://w3c.github.io/wai-website/tutorials/page-structure/headings/ (Needs images and other things prepared in the actual tutorial repositories, but we do indeed have highlight boxes for that content.)

I think they all work well, if there is something missing, feel free to open a different issue.
