### ISSUE TITLE
Collect Feedback on Style Tiles

### ISSUE THREAD

**Issue by James-Green** [w3c/wai-website-design#11]

**Comment by happywebdiva** [comment]
I'm happy to take this on for the September sprint.  I think of it more as gathering feedback than "evaluating" -- though of course there is evaluation especially for WCAG 2.0 AA compliance.  What I will do is listen and take notes on feedback as Sharron unrolls style tile submissions during Sept. 7 meeting.  Then after the meeting I'll reach out individually to primary stakeholders who weren't on the call (at least Judy and Shawn) and team members who weren't able to be on the call.  Also, it may be that the feedback leads to some minor adaptations of some style tiles and I'm happy to include that in this work if I'm leading it.

**Comment by brewerj** [comment]
I keep looking at the info tiles, and keep having concerns. It is good to see that the area has gotten reduced somewhat, but my overall impression is that much of the "real estate" of the "above the fold" area of the page is still taken up with a few large images, and large fonts, plus large panels of non-linked, non-interactive space. So this worries me. We have so many good resources to circulate. I think that these panels could be made smaller, with narrower margins, less white space below them, and shallower panel height so that the reader can get to the material under this more quickly.

**Comment by yatil** [comment]
@brewerj This issue is closed since 2016 and about the StyleTiles which we used to get the design direction. I think you refer to the illustration on top of the homepage. Can you please open a new issue here? https://github.com/w3c/wai-website/issues

Remember nobody is actively monitoring closed issues, so your comments there will be missed unless you also re-open the issue.
