### ISSUE TITLE
highlight color

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-website-design#120]
Old css had:

.changed {
	background: #FFFFCC;
}

We'll want something like that for new site as well.

Let's go with that background color for now (unless someone speaks up strongly for a different color).

I don't feel strongly about keeping "changed" or making it something else -- so feel free to pick other if you want, @yatil

**Comment by yatil** [comment]
For highlights, we can use the HTML5 `<mark>` element which uses a yellow highlight color and adds appropriate semantics. It currently uses the browser styles because it was not specified that it should change.

We don’t have `#FFFFCC` in the colors for the redesign, however, we have the gold color: `#eed009` that we use throughout the site.

`#FFFFCC` is also a very subtle against the background, I wonder if that is sufficient contrast to be sufficient for WCAG 2.1 and looks a bit broken to me:

<img width="1022" alt="" src="https://user-images.githubusercontent.com/58862/36194502-39bb7f76-116a-11e8-9b3a-a2f0358a6772.png">

Gold (`#eed009`) is a bit too contrasty, it seems:

<img width="1026" alt="" src="https://user-images.githubusercontent.com/58862/36194575-7a45d88e-116a-11e8-8c9b-f61f45bcde6d.png">

What about using the gold color with a 35% opacity (`rgba(234,208,71,.35)`):

<img width="996" alt="" src="https://user-images.githubusercontent.com/58862/36194659-e05ee21e-116a-11e8-825a-9101c14ce41c.png">

**Comment by iamjolly** [comment]
I like that gold with 35% opacity. It’s like 35% of 24 karat, so... 8.4 karat gold!

**Comment by shawna-slh** [comment]
+1 to the gold color with a 35% opacity (rgba(234,208,71,.35)):
