### ISSUE TITLE
Design Mockups: In-page nav on left instead of right. [medium]

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-website-design#38]
Level: [medium] I would like to get input from others.
Reference: [26 Jan mockups](https://projects.invisionapp.com/share/H299QZZGZ#/screens/215895929), screen 5 of 9

Some concern with in-page navigation on the left. W3C and WAI site users are used to site nav on the left and in-page nav on the right (e.g., [Mobile page](https://www.w3.org/WAI/mobile/)). My gut is that it's OK to have site-wide nav at the top and *no nav* on the left, but it could be confusing to some users to have in-page nav on the left. (from [13 Dec e-mail](https://lists.w3.org/Archives/Public/public-wai-eo-site/2016Dec/0006.html) and Nov F2F)

Also, the Tutorial mockup has different navigation on the left.

Perhaps the WAI site is so different from current w3.org and previous WAI site, that it won't mess up too many people too much? On the other hand, why risk confusing users? Why have in-page on the left instead of the right?

**Comment by brewerj** [comment]
I was wondering about this issue when viewing the design mock-ups. Could Alicia help explain the pros and cons that she sees with regard to left-side vs right-side nav, at least for left-to-right scripts? (Obviously this positioning might be reversed for right-to-left scripts.) From my perspective, the right-side nav gives a cleaner look to the page, but it seems less obvious, and more likely to be overlooked even though it contains crucial information. I'd be interested to hear other people's feedback on this point as well.

**Comment by bakkenb** [comment]
Level: [medium-strong] 

I like the in-page navigation much better on the left side, rather than the right side. 

Rationale:
(A) I believe people will quickly become familiar with the top overall site navigation. It will not change from page to page, and could even stay present when using tools like the quickref or the tools list (the latter is left for a separate discussion). When presented with a left side in-page navigation, I do not believe that users would be confused in thinking that all of a sudden the WAI site navigation was now on the left side as well as the top. Most in-page navigation is quickly distinguishable to the content of the currently viewed resource.

(B) Most of the time the main content is left aligned. With a clean left side in-page navigation box, the left aligned content will fit nicely against the navigation box with consistent spacing from page to page. When we put the in-site navigation on the right, the navigation box tends to spacially (made up word) fight with the jagged right side of the main content. Usually the box alignment is "in-line with text" causing the text underneath the nav box to go all the way back to the right side of the window. That is normal, but it just looks odd. It looks like we just shoved the in-page nav box in there because we had no where else to put it.

(C) I think the right side of the page should be reserved for call-outs, related content, more information, etc. and not be confused with navigation. If we keep navigation on top (for WAI site) and on the left (for in-page and tool) and are consistent with that, then the site will be less confusing when other additional key information or links are added to the right side.

**Comment by lakeen** [comment]
+1 to Brent - [strong]

**Comment by yatil** [comment]
I don’t feel strongly left or right nav. If the in-page navigation is on the left and also sub-pages can be linked on the left, it can be confusing if both elements look too similar.

**Comment by James-Green** [comment]
resolution to leave on left.
