### ISSUE TITLE
Design Mockups: Recognition of WAI and W3C [strong]

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-website-design#43]
Please read/skim: [Design Parameters](https://www.w3.org/WAI/EO/wiki/Design_Parameters)

For input:
* How does this visual design reinforce WAI brand and strong relationship with [W3C](https://www.w3.org/)?
* Any suggestions for strengthening WAI brand and W3C &mdash; while being awesome, modern design? :-)

**Comment by bakkenb** [comment]
Good point @slhenry. I believe that the design supports a strong relationship to the W3C as the colors are fairly similar and the design is cleaner. 

What I am confused about is what the WAI brand was. To me there was not a strong branding to the WAI site. In a few cases, colors changed with some resources, What was consistent was to top banner, which I think most feedback was a desire to modernize that part and re-brand the WAI site. 

In my opinion, this is a cleaner look and feel, that compliments the W3C site very closely. 

Personally I wish we could find a small, simple graphic that could go along with "Web Accessibility Initiative" so that the graphic is always present and recognizable on any WAI page or WAI resource. It could even be the letters "WEI." Something very simplistic yet very modern looking.

- Consumer Reports just finished updating their site with a new look and feel. They incorporated [a very modern feeling graphic to go along with their name](http://www.consumerreports.org/). A simple "CR" in a thick block text.  
- Library of Congress has something simple that is not letters. They incorporated [a simple book that resembles a flag along with their name](https://www.loc.gov/).
- Amazon has the yellow arrow indicating "everything from A to Z" for sale. 
- Microsoft has the four square colors ever-present.

I think if we could have something like this it would help create a new recognizable brand.

**Comment by lakeen** [comment]
+1 to Brent's comments about the look and feel of the new design.  I think Alicia is doing a really good job complimenting the W3C look and feel.  

The second part of Brent's comments is talking about logo design/brand identity which a big effort.  In my opinion, if done right should include the W3C and all of its properties.

**Comment by yatil** [comment]
I would totally know what that “WAI Brand” actually is. Is it the colors, the fonts, the logo (in which case that is design). I have sent a longer email with detailed questions some time ago to determine what that “Brand” actually is or which components are perceived as ”the WAI Brand”. I think a cohesive style, playing off the W3C style is much more important than consistency with the (somewhat inconsistent) old site.

+1 to come up with a word mark or something, but I don’t think that needs to be prioritized for this redesign.

**Comment by sharronrush** [comment]
The new design matches the W3C brand much more effectively than the old one

**Comment by James-Green** [comment]
resolution, the TF feels that the design does support the brand and connection to W3.  no changes now as it is out of scope, but may consider an "icon" like Brent mentioned (CR or LOC) during a true re-branding effort in the future.
