### ISSUE TITLE
[Nav EOWG] Combine Implementation guidance in one menu

### ISSUE THREAD

**Issue by vmmiller** [w3c/wai-website-design#81]
I feel that "Write & Design" and "Code & Develop" could be combined into "Design & Develop".  There are reasons to support two separate menus but, at the same time, I think "Write and Design" is still lacking in such resources.  

My question is:  could "Write & Design" and "Code & Develop" be combined into "Design & Develop"?  
To fill the menu space used by "Write & Design", we could possibly "bring back" the "Standards/Guidelines" link to the main navigation menu bar ((after "Training & Advocates").

**Comment by nrhsinclair** [comment]
+1 on Design & Develop

**Comment by bakkenb** [comment]
+1 
There currently is not much sub-pages in these two main navigation categories. I think they look better combined and will probably simplify searching by main navigation for people looking for these types of resources.

Also, as stated in issue #80, I strongly agree with bringing "Standards/Guidelines" down into the main navigation so that it will be more visible (or less overlooked).

**Comment by lakeen** [comment]
+1 Design & Develop

**Comment by shawna-slh** [comment]
Implementation guidance resources under "Design & Develop".

Resolved in [25 August telecon](https://www.w3.org/2017/08/25-eo-minutes.html)
