### ISSUE TITLE
[Home page] Top Feature: Tutorials

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-website-design#91]
Some ideas:

**Tutorials**
Get guidance on developing content that is accessible to people with disabilities.
button: [Web Accessibility Tutorials](@@)

**Web Accessibility Tutorials**
Get guidance on developing content that is accessible to people with disabilities.
button: [Tutorials](@@)

**Tutorials**
Get guidance on developing content that is accessible to people with disabilities from the [Web Accessibility Tutorials](@@)

**Web Accessibility Tutorials**
Get guidance on [page structure](@@), [menus](@@), [images](@@), [tables](@@), [forms](@@), [carousels](@@)

**Tutorials**
Get guidance on developing accessible [page structure](@@), [menus](@@), [images](@@), [tables](@@), [forms](@@), [carousels](@@)

**Comment by bakkenb** [comment]
I like this one...  (also dropped the word "Get")

> **Web Accessibility Tutorials**
> Guidance on developing content that is accessible to people with disabilities.
> button: [Tutorials](https://www.w3.org/WAI/tutorials/)

Rationale: I like the name of the resource up on top because in the [mockup ](https://w3c.github.io/wai-website-components/components/preview/example-home.html)the box starts with "Featured Resource" - then I think we should have the name of that resource as the next thing people read. 

Dropped "Get" because it sounds grammatically incorrect. "Receive" sounds better, but I would prefer just dropping the word to simplify.

**Comment by shawna-slh** [comment]
@yatil - I say go with Brent's suggestion for the usability testing.

>**Web Accessibility Tutorials**
Guidance on developing content that is accessible to people with disabilities.
_button:_ [Tutorials]

**Comment by yatil** [comment]
Done. The button stays “Read more” as the whole box is a link and repeating tutorials at the end of the link makes little sense, IMHO.
